print: basic_print_tutorial.c
	gcc basic_print_tutorial.c -o basic_print_tutorial
pointer: basic_pointers_tutorial.c
	gcc basic_pointers_tutorial.c -o basic_pointers_tutorial
oop: basic_OOP_tutorial.c
	gcc basic_OOP_tutorial.c -o basic_OOP_tutorial
memory: basic_memory_tutorial.c
	gcc basic_memory_tutorial.c -o basic_memory_tutorial