cpp-math: cpp-math.cc
	g++ -c cpp-math.cc -o cpp-math.o
c-math: c-math.c
	gcc -c c-math.c -o c-math.o
c-string: c-style-strings.c
	gcc -g c-style-strings.c -o c-style-strings
c-io: c-io.c
	gcc -g c-io.c -o c-io
c-memory: c-memory.c
	gcc -c c-memory.c -o c-memory